[profile.default]
auto_detect_solc = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 2_000
bytecode_hash = "none"
fs_permissions = [{ access = "read", path = "./" }]
auto_detect_remappings = false
libs = ["lib"]
ffi = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=training/damn-vulnerable-defi/lib/openzeppelin-contracts/",
    "@safe-global/safe-smart-account/=training/damn-vulnerable-defi/lib/safe-smart-account/",
    "dvd/=training/damn-vulnerable-defi/",
    "poc/=src/poc/",
    "uniswap/v3-periphery/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/=lib/v3-core/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/contracts/"
]

[fmt]
line_length = 100

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
